apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name:  {{ include "os-iptables.fullname" . }}
  labels:
    {{- include "os-iptables.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: [ "get" ]

