apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "os-iptables.fullname" . }}
  labels:
    {{- include "os-iptables.labels" . | nindent 4 }}
subjects:
  - kind: User
    name: {{ include "os-iptables.serviceAccountName" . }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{ include "os-iptables.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
